apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: simple-task
spec:
  stepTemplate:
    env:
      - name: BUILD_NUMBER
        valueFrom:
          fieldRef:
            fieldPath: metadata.annotations['devops.cloud.ibm.com/build-number']
  steps:
    - name: simple-step
      image: icr.io/continuous-delivery/pipeline/pipeline-base-image
      command: ["/bin/bash", "-c"]
      args:
        - echo -e "Start Pipeline Run - Build Number $BUILD_NUMBER";
          sleep 30;
          echo "Build $BUILD_NUMBER Complete";
